/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as CatalogRouteImport } from './catalog'
import { Route as DownloaderRouteImport } from './downloader'
import { Route as HistoryRouteImport } from './history'
import { Route as LibraryRouteImport } from './library'
import { Route as ScannerRouteImport } from './scanner'
import { Route as ScheduleRouteImport } from './schedule'
import { Route as SettingsRouteImport } from './settings'
import { Route as AnimeIndexRouteImport } from './anime.index'
import { Route as AnimeIdRouteImport } from './anime.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloaderRoute = DownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/downloader': typeof DownloaderRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/scanner': typeof ScannerRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/anime/': typeof AnimeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/downloader': typeof DownloaderRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/scanner': typeof ScannerRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/anime': typeof AnimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/downloader': typeof DownloaderRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/scanner': typeof ScannerRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/anime/': typeof AnimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/downloader'
    | '/history'
    | '/library'
    | '/scanner'
    | '/schedule'
    | '/settings'
    | '/anime/$id'
    | '/anime/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/downloader'
    | '/history'
    | '/library'
    | '/scanner'
    | '/schedule'
    | '/settings'
    | '/anime/$id'
    | '/anime'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/downloader'
    | '/history'
    | '/library'
    | '/scanner'
    | '/schedule'
    | '/settings'
    | '/anime/$id'
    | '/anime/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DownloaderRoute: typeof DownloaderRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  ScannerRoute: typeof ScannerRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  AnimeIdRoute: typeof AnimeIdRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloader': {
      id: '/downloader'
      path: '/downloader'
      fullPath: '/downloader'
      preLoaderRoute: typeof DownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DownloaderRoute: DownloaderRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  ScannerRoute: ScannerRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  AnimeIdRoute: AnimeIdRoute,
  AnimeIndexRoute: AnimeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
