// Fuente única de canales IPC: preloads, globals.d.ts y registro de handlers salen de aquí.
// Los .js de los preloads los genera scripts/generate-preload.mjs; no se editan a mano.

// invoke: renderer -> main (ipcMain.handle)
export const INVOKE_CHANNELS = [
  'get-preloaded-data',
  'get-providers',
  'get-active-provider',
  'set-active-provider',
  'get-connectivity-status',
  'get-download-history',
  'clear-download-history',
  'remove-history-entry',
  'remove-history-entries',
  'open-folder',
  'window-minimize',
  'window-toggle-maximize',
  'window-close',
  'force-close-app',
  'window-get-state',
  'open-external-url',
  'app-restart',
  'add-to-queue',
  'cancel-download',
  'pause-download',
  'cancel-episode',
  'pause-episode',
  'resume-episode',
  'skip-episode',
  'skip-server',
  'clear-queue',
  'remove-from-queue',
  'resume-download',
  'retry-failed-download',
  'open-anime-folder',
  'get-queue',
  'get-settings',
  'get-default-settings',
  'save-settings',
  'get-image-base64',
  'get-home-data',
  'get-schedule',
  'get-catalog',
  'get-filters-data',
  'search-anime',
  'get-details',
  'get-episode-thumbs',
  'get-anilist-banner',
  'search-anilist',
  'set-anilist-link',
  'remove-anilist-link',
  'select-folder',
  'search-trailer-id',
  'rename-anime-files',
  'preview-rename-anime-files',
  'preview-reorder-episodes',
  'scan-downloads',
  'rename-folder',
  'delete-folder',
  'relink-folder',
  'scan-episodes',
  'play-video',
  'delete-video',
  'get-folders-for-reorder',
  'reorder-episodes',
  'get-video-thumbnail',
  'app-update-check',
  'app-update-download',
  'app-update-install',
  'get-app-version',
  'get-splash-icon',
  'get-storage-stats',
  'get-server-stats',
  'clean-cache',
  'clean-thumbnails',
  'get-app-paths',
  'open-app-path',
  'export-settings',
  'import-settings',
  'import-custom-sound',
  'delete-custom-sound',
  'read-sound-data',
  'get-system-info',
  'get-log-page',
  'get-log-filenames',
  'delete-log-files',
  'export-diagnostics',
  'delete-log-entries',
  'renderer-ready',
] as const;

// send: renderer -> main (ipcMain.on). Solo log-error.
export const SEND_CHANNELS = ['log-error'] as const;

// evento: main -> renderer (webContents.send / api.on)
export const EVENT_CHANNELS = [
  'app-ready',
  'confirm-app-close',
  'window-state-changed',
  'queue-update',
  'queue-progress',
  'history-updated',
  'download-started',
  'episode-downloaded',
  'app-update-status',
  'dl-log',
  'dl-status',
  'dl-log-progress',
] as const;

// eventos del splash: viven solo en splashPreload, fuera del preload principal
export const SPLASH_EVENT_CHANNELS = ['splash-status'] as const;

export type InvokeChannel = (typeof INVOKE_CHANNELS)[number];
export type SendChannel = (typeof SEND_CHANNELS)[number];
export type EventChannel = (typeof EVENT_CHANNELS)[number];
export type SplashEventChannel = (typeof SPLASH_EVENT_CHANNELS)[number];
